// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfn8wSjpdk55Ra5bgrRv6E7yUIVz5cDEE',
    appId: '1:766174905426:web:e21b69f9e8fe99cdeb0b8b',
    messagingSenderId: '766174905426',
    projectId: 'mranti-a39d6',
    authDomain: 'mranti-a39d6.firebaseapp.com',
    databaseURL: 'https://mranti-a39d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mranti-a39d6.appspot.com',
    measurementId: 'G-5J2X8RWDCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs_8_FNguob11Mh7k4XwchgZ7VTJvZ6wM',
    appId: '1:766174905426:android:c7462a7868c2dad4eb0b8b',
    messagingSenderId: '766174905426',
    projectId: 'mranti-a39d6',
    databaseURL: 'https://mranti-a39d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mranti-a39d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWVY3FeHIMCzv4WqcuEoutQljP4_ej6aM',
    appId: '1:766174905426:ios:81b329bfc4ce5c72eb0b8b',
    messagingSenderId: '766174905426',
    projectId: 'mranti-a39d6',
    databaseURL: 'https://mranti-a39d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mranti-a39d6.appspot.com',
    iosBundleId: 'com.example.aishield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWVY3FeHIMCzv4WqcuEoutQljP4_ej6aM',
    appId: '1:766174905426:ios:0e2465411e4b59fceb0b8b',
    messagingSenderId: '766174905426',
    projectId: 'mranti-a39d6',
    databaseURL: 'https://mranti-a39d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mranti-a39d6.appspot.com',
    iosBundleId: 'com.example.aishield.RunnerTests',
  );
}
